/**
Polygon model for Google Map
@author: Jofel Bayron
*/

var Polygon = (function(){

    function Polygon(map){
        this.Map = map;
    }

    Polygon.prototype = {
        polygons: {},
        add: function(gridcode, coordinates){
            /**
               @param: gridcode -> gridcode autogenerated by cartodb
                       coordinates -> list of {lat, long} object
             */
            var points = [];
            for (var i = 0; i < coordinates.length; i++) {
                var coord = coordinates[i];
                points.push({
                    lat: coord[1],
                    lng: coord[0]
                });
            }

            this.polygons[gridcode] = new google.maps.Polygon({
                paths: points,
                strokeColor: '#FF0000',
                strokeOpacity: 0.8,
                strokeWeight: 1
            });
            this.polygons[gridcode].setMap(this.Map);
        },
        
        get: function(key){
            /**
               @param: key -> string
               
               return a Polygon object
             */
            return this.polygons[key];
        },
        all: function(){
            return this.polygons;
        }
    };
    
    return Polygon;
})();
